### ISSUE TITLE
Plugin Installed but not appearing on Jenkins 2.319.1

### ISSUE THREAD

**Issue by mode19** [jenkinsci/build-history-metrics-plugin#20]
Hi I installed this plugin on Jenkins 2.319.1

In the plugin manager view it appears as installed @ version: 97.vdcf3aa48af8d

However, I do not see any table rendered on my job pages. Also, I noticed, there is no sample on the plugin home page to show what the plugin looks like: https://plugins.jenkins.io/build-history-metrics-plugin/

Please let me know if I can provide any debug information.

**Comment by jonesbusy** [comment]
I think the plugin looks a bit abandonned.

I did some tentative to refresh it on https://github.com/jenkinsci/build-history-metrics-plugin/pull/40

But didn't do any other extra visual tests with recent Jenkins version.

**Comment by jonesbusy** [comment]
I confirm that it works on this PR https://github.com/jenkinsci/build-history-metrics-plugin/pull/40 using a freestyle job. Not sure if pipelines are supported.

Perhaps the table need also some refresh

![Image](https://github.com/user-attachments/assets/b6ee0513-b3b8-47ad-95bd-f780814c7757)

**Comment by jonesbusy** [comment]
Hi,

Table and column should work on [116.v1d3fee4e91d9](https://github.com/jenkinsci/build-history-metrics-plugin/releases/tag/116.v1d3fee4e91d9)

Hovewer I'm not able to display any graph. 

I recently adopted the plugin, so not sure how it should look like.
